Dev/landing page
ExpanseServices/Website pull request #5
Opened 2021-08-02 18:19 UTC by mastercodingbear

Not finished unit test.

2021-08-02 21:35 UTC, Matt-Mckeller commented
the #1 most important thing is that the page is not responsive right now

I'll work on getting a designer on this asap. The designer who created this is working on the pricing page and has a full time job m-f so he can only work weekends

Maybe we can still get this to look a little better on smaller screens before we get a complete mobile design?

2021-08-02 21:45 UTC, Matt-Mckeller commented
not a fan of the animation on the hero section, seems distracting

maybe if it was slowed down like 10-20x but I would have to see that

2021-08-02 22:24 UTC, Matt-Mckeller commented
i like the quote movement on the testemonial

2021-08-02 22:31 UTC, Matt-Mckeller commented
could I see some other options for the explore / get started button animation?

2021-08-02 22:37 UTC, Matt-Mckeller commented
updated the button text on get started

2021-08-03 00:04 UTC, Matt-Mckeller reviewed
I kind of like the ripple / wave effect below the our services section but I think the green background does not look nearly as good with this. I think the positioning of the green blob in the background and the section divider is really important to the visual appeal

Maybe something could be done to improve it but I'm not sure. Would have to see some examples

----

I think the animations for the process section and statistics section are kinda cool, but could we take them off a timer and instead make them work with the scroll position? as user scrolls down animation progresses, scroll up maybe it reverts ( or maybe it stays finished ) 

the timing for the initiation of the animations for the process and statistics section seem off too. I actually am having trouble viewing them because they start before my scrolling can get there 

I know the animations are extras!!! I really really appreciate the work on those. I think the interactivity/motion added to this page really takes it up another level

----
For the buttons I think that if the arrow also changed color it would look much better

button arrow and text alignment is off ( and was also off on mockup, I did some updates for that too )

--
i love the quote movement on hover 


Fantastic work! I'm so happy to see this come to life!!! You're doing great and I could not be happier :)

I would say that we can put the unit testing off until the rest is at 100%. I definitely want unit testing to be part of our standard process, and to be included in Expanse's website source code but most important is going to be getting this functional and usable. My vision is to make this an evolving code base which we reference as a template / example for future projects. This will take some time to get right XD

2021-08-03 00:05 UTC, Matt-Mckeller commented on components/ui/buttons/call-to-action-button.tsx
> +const CallButton = styled.button`
StyledCallToActionButton ?

2021-08-03 00:14 UTC, Matt-Mckeller commented on components/ui/containers/component-containers/home/consultation.component.tsx
> +            color: "Silver"
can we put this into the color config file and reference it there? also would prefer the hex version #C6C6C6

2021-08-03 00:14 UTC, Matt-Mckeller commented on components/ui/containers/component-containers/home/consultation.component.tsx
> +    color: #DBD1FE;
color config or some centralized location pls

2021-08-03 00:20 UTC, Matt-Mckeller commented on components/ui/containers/page-sections/home/testimonial-section.tsx
> +// import clsx from  'clsx';
remove?

2021-08-03 00:22 UTC, Matt-Mckeller commented on components/ui/layout/header.tsx
> +  // console.log(router.pathname, router.basePath);
remove when finished

2021-08-03 00:24 UTC, Matt-Mckeller commented
gsap-bonus.tgz needed?

2021-08-03 00:24 UTC, Matt-Mckeller commented on next.config.js
>  // const withImages = require('next-images')
remove

2021-08-03 00:25 UTC, Matt-Mckeller commented on package.json
> +    "gsap": "./gsap-bonus.tgz",
any reason we are importing it like this? can we reference a repo?

2021-08-03 00:28 UTC, Matt-Mckeller commented on pages/_document.tsx
> +MyDocument.getInitialProps = async (ctx) => {
fantastic, good comments

2021-08-03 00:29 UTC, Matt-Mckeller commented on pages/index.tsx
> +// Index.getInitialProps = ({ req }) => {
?  Don't we need this for server side rendering?

2021-08-03 00:33 UTC, Matt-Mckeller commented on pages/_app.tsx
> +            <CssBaseline />
Oh! Cool! Did you also remove the normalize css?

2021-08-03 00:34 UTC, Matt-Mckeller commented on components/ui/layout/header.tsx
> +  // console.log(router.pathname, router.basePath);
oh, these are my logs lol

2021-08-03 00:34 UTC, Matt-Mckeller requested changes
:) see comments! Great job, I can tell you put a lot of work into this and I appreciate it

2021-08-03 00:50 UTC, Matt-Mckeller commented
also please make sure this works on all modern browsers, I did not test this

2021-08-03 17:02 UTC, Matt-Mckeller approved these changes

2021-08-03 17:02 UTC, merged

2021-08-04 11:51 UTC, mastercodingbear commented on package.json
> +    "gsap": "./gsap-bonus.tgz",
drawing line animation and counter animation are implemented by gsap

2021-08-04 11:53 UTC, mastercodingbear commented
> gsap-bonus.tgz needed?

this has bonus plugins.
like ScrollTrigger, Textplugin. And I thinkg we can make more animations with gsap.

2021-08-04 12:13 UTC, Matt-Mckeller commented
> > gsap-bonus.tgz needed?
> 
> this has bonus plugins.
> like ScrollTrigger, Textplugin. And I thinkg we can make more animations with gsap.

can we import from github instead of a tgz file?